version: '3'

services:
  bot:
    image: <image name>
    deploy:
      cap_drop:
        - NET_RAW
        - SYS_ADMIN
    environment:
      - TOKEN=<bot token>
      - APPLICATION_ID=<discord bot application id>
      - PREFIX=<bot prefix>
      - OWNER=<discord bot owner>
      - SYNC_COMMANDS_GLOBALLY=<true or false>
      - OWM_API_KEY=<openweathermap api key>
    volumes:
      - ./:/app
    working_dir: /app
  